version: '3.9'

services:
  # USER SERVICE
  user-service:
    build: ./user-service
    container_name: user-service
    env_file:
      - ./user-service/.env
    ports:
      - "3001:3000"
    depends_on:
      - user-db

  user-db:
    image: mongo:7
    container_name: user-db
    restart: always
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_DATABASE: userdb
    volumes:
      - user_data:/data/db

  # NUTRITION SERVICE
  nutrition-service:
    build: ./nutrition-service
    container_name: nutrition-service
    env_file:
      - ./nutrition-service/.env
    ports:
      - "3002:3000"
    depends_on:
      - nutrition-db

  nutrition-db:
    image: mongo:7
    container_name: nutrition-db
    restart: always
    ports:
      - "27018:27017"
    environment:
      MONGO_INITDB_DATABASE: nutritiondb
    volumes:
      - nutrition_data:/data/db

  # WORKOUT SERVICE
  workout-service:
    build: ./workout-service
    container_name: workout-service
    env_file:
      - ./workout-service/.env
    ports:
      - "3003:3000"
    depends_on:
      - workout-db

  workout-db:
    image: mongo:7
    container_name: workout-db
    restart: always
    ports:
      - "27019:27017"
    environment:
      MONGO_INITDB_DATABASE: workoutdb
    volumes:
      - workout_data:/data/db

  # SESSIONS SERVICE
  sessions-service:
    build: ./sessions-service
    container_name: sessions-service
    env_file:
      - ./sessions-service/.env
    ports:
      - "3004:3000"
    depends_on:
      - sessions-db

  sessions-db:
    image: mongo:7
    container_name: sessions-db
    restart: always
    ports:
      - "27020:27017"
    environment:
      MONGO_INITDB_DATABASE: sessionsdb
    volumes:
      - sessions_data:/data/db

volumes:
  user_data:
  nutrition_data:
  workout_data:
  sessions_data:
