version: "3.9"

services:
  mysql:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: micocas1+
      MYSQL_DATABASE: users_db
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - fitlife-network
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure

  mongodb:
    image: mongo:6
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    networks:
      - fitlife-network
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure

  rabbitmq:
    image: rabbitmq:3-management
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    ports:
      - "5672:5672"
      - "15672:15672"
    networks:
      - fitlife-network
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure

  nutrition-service:
    image: fitlife-nutrition-service:latest
    ports:
      - "4000:4000"
    environment:
      MONGODB_URI: mongodb://mongodb:27017/nutrition_db
    networks:
      - fitlife-network
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure

  users-service:
    image: fitlife-users-service:latest
    ports:
      - "3002:3002"
    networks:
      - fitlife-network
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure

  notifications-service:
    image: fitlife-notifications-service:latest
    networks:
      - fitlife-network
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure

  workout-service:
    image: fitlife-workout-service:latest
    ports:
      - "3004:3004"
    networks:
      - fitlife-network
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure

  sessions-service:
    image: fitlife-sessions-service:latest
    ports:
      - "3003:3003"
    env_file:
      - ./sessions-service/.env
    networks:
      - fitlife-network
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure

volumes:
  mysql_data:
    driver: local
  mongo_data:
    driver: local

networks:
  fitlife-network:
    driver: overlay
